title: Pedro Scarpellini
description: > # this means to ignore newlines until "baseurl:"
  Kotlin blog written by Pedro Scarpellini dos Santos mobile developer.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pedroscar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pedro Santos # add your name
author-img: pedro-santos.jpg # add your photo
about-author: I am a seasoned mobile developer with over four years of hands-on experience, specializing in Kotlin. I have a proven track record, having worked with renowned multinational companies such as IBM and Indra.
social-twitter: PeScarpellini # add your Twitter handle
social-github: pedroscar
social-linkedin: pedro-santos-android
social-email: pedro.scarpellini@gmail.com # add your Email address

# Disqus
discus-identifier: pedroscarpellini # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
